show databases;
use db10;
select * from employee;
select * from employee where employee_name like 'm%';
select * from employee where employee_name like '%h';
select * from employee where employee_name like '__y%';
select id,employee_name,salary from employee;
select id as "employee_id",employee_name,salary as "employee_salary" from employee;
select id as "employee_id",employee_name,salary as "employee_salary", salary-(salary*10/100) as "gross_salary" from employee;
select id,employee_name from employee;
select concat(id,'     ',employee_name) as "id and name" from employee;
select count(*) from employee;
select sum(salary) from employee;
select max(salary) as "maximum_salary" from employee;
select min(salary) as "minimum_salary" from employee;
select sum(salary) as "total salary",max(salary) as "maximum_salary",min(salary) as "minimum_salary",avg(salary) as "average_salary" from employee;
create table department(dept_id varchar(20) , dept_name varchar(20) not null, location varchar(20) unique, country varchar(20) default 'india' , primary key(dept_id));
desc department;
insert into department values('cts_1001','training','bangalore','india');
insert into department values('cts_1002','training','bangalore','india');
insert into department(dept_id,dept_name,location) values('cts_1003','transport','chennai');
select * from department;
insert into department(dept_id.location) values('cts_1006','kolkata');
show tables;
select * from employee;
rename table department to emp_dept;
show tables;
create user aditya identified by 'qwerty123!@#';
grant create on *.* to aditya;